import matplotlib.pyplot as plt
import pandas as pd
dataset = pd.read_csv(r'C:\Users\Aleksey\Desktop\real_estate.csv', index_col=0, parse_dates=True)
plt.hist(dataset['Transact Date'])
plt.title('Transact Date')
plt.show()
plt.hist(dataset['Age'])
plt.title('Age')
plt.show()
plt.hist(dataset['Distance To Transport'])
plt.title('Distance To Transport')
plt.show()
plt.hist(dataset['Shops'])
plt.title('Shops')
plt.show()
plt.hist(dataset['Latitude'])
plt.title('Latitude')
plt.show()
plt.hist(dataset['Longitude'])
plt.title('Longitude')
plt.show()
plt.hist(dataset['Price'])
plt.title('Price')
plt.show()
